### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by jonhoo**
It'd be great if we could issue a point release with these fixes too!

### CODE REVIEW

**Comment by jonhoo** [comment]
@zonyitoo thanks! could you issue a new minor release with this fix too please?

**Comment by zonyitoo** [comment]
I will release it in v0.5.0.

**Comment by jonhoo** [comment]
I think this only needs to be `0.4.2`? Unless there are also other changes?

**Comment by zonyitoo** [comment]
It would be a breaking change. Someone may be depending on those old libraries.

**Comment by jonhoo** [comment]
Since `memcached-rs` does not have `rand` in any of its public-facing APIs, it is not a breaking change. If someone else depends on `rand 0.5`, then this change to `memcached-rs` will not break their code. `cargo` will do the right thing and download and compile `0.5` and `0.7` separately.

**Comment by zonyitoo** [comment]
I have also upgraded to edition 2018. Hopefully that wouldn't break anyone's code.

**Comment by zonyitoo** [comment]
Uploaded v0.4.2.

**Pull request merged**
