### PR TITLE
Panic on no keys in multi-operations

### PR DESCRIPTION
**Pull request by grcooper**
When playing with this client, I ran into a weird error and realized on multi-commands when sending no keys you got a strange error because we couldn't unwrap no keys.

~~I waffled on returning just an empty Ok vs panicking with an assert, but I think that sending no keys isn't something that should be "invalid" it should just early out and not actually make any attempt to serve from the datastore.~~

I made asserts and panicked when there were no keys passed in so the error messages were more clear.

Let me know if you agree with my approach, I also added in some additional tests. I'm not super well versed in Rust so if my approach to organizing the tests is wrong please let me know and I can adjust.

### CODE REVIEW

**Comment by zonyitoo** [comment]
Key shouldn't be empty. I think it should be an error instead of returing an Empty value.

**Comment by grcooper** [comment]
@zonyitoo addressed - changed to panic instead.

**Comment by zonyitoo** [comment]
Clippy should complain that `.len() > 0` should be replaced by `.empty()` :P

**Comment by grcooper** [comment]
I don't think `empty()` exists in this context?
Screenshot 2023-08-28 at 1 16 01 PM

https://doc.rust-lang.org/std/collections/btree_map/struct.Keys.html

We would have to collect the keys into a collection then use `.empty()` which feels like an unneeded additional step.

**Pull request merged**
